### ISSUE TITLE
Fails to Update

### ISSUE THREAD

**Issue by ryanmac8** [custom-components/sensor.personalcapital#14]
Component fails to update. Will work after the initial verification but all future updates fails. I have to remove the session file and restart Home Assistant to make it functional again. 

`Update for sensor.pc_other_asset fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/personalcapital/sensor.py", line 219, in update
    data = self._rest.data.json()['spData']
KeyError: 'spData'`

**Comment by ryanmac8** [comment]
Found the issue. Personal Capital automatically set Multi-Factor Authentication to Every Sign In. Can change this to For New Devices and the component will work just fine.
