### ISSUE TITLE
Integration Stopped Working Nov 16th?

### ISSUE THREAD

**Issue by olines** [custom-components/sensor.personalcapital#19]
Hi, the personalcapital integration 0.1.2 seems to have stopped working on Nov 16th?

Home Assistant 2021.11.5

Entity not available:

**Comment by raman325** [comment]
https://github.com/haochi/personalcapital/issues/20

**Comment by raman325** [comment]
Looks like this PR fixes it: https://github.com/haochi/personalcapital/pull/21

**Comment by sanghviharshit** [comment]
For anyone looking for the easiest way to get this working again - I forked this repo and got it working with the fixes mentioned above. You can switch over to https://github.com/sanghviharshit/sensor.personalcapital (add it as custom repository and reinstall personal capital using HACS)

**Comment by ecoen66** [comment]
@sanghviharshit I uninstalled PC, and re-installed from your custom repo, but now I get:

Logger: homeassistant.components.sensor
Source: custom_components/personalcapital/sensor.py:120 
Integration: Sensor (documentation, issues) 
First occurred: 8:51:12 AM (1 occurrences) 
Last logged: 8:51:12 AM

Error while setting up personalcapital platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/personalcapital/sensor.py", line 120, in setup_platform
    from personalcapital import PersonalCapital, RequireTwoFactorException, TwoFactorVerificationModeEnum
  File "/usr/local/lib/python3.9/site-packages/personalcapital/__init__.py", line 1, in <module>
    from .personalcapital import PersonalCapital, RequireTwoFactorException, TwoFactorVerificationModeEnum
  File "/usr/local/lib/python3.9/site-packages/personalcapital/personalcapital.py", line 1, in <module>
    import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'

**Comment by sanghviharshit** [comment]
I think it's still using the old `personalcapital` dependency installed with the old component. Can you uninstall both old and new components completely, restart HA, and then install the new component?

**Comment by ecoen66** [comment]
Really?  I would think that that last part indicates that it is using the new personalcapital:

File "/usr/local/lib/python3.9/site-packages/personalcapital/personalcapital.py", line 1, in
import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'

**Comment by sanghviharshit** [comment]
Yes, you are right. Although I have listed `cloudscraper` as a requirement here https://github.com/sanghviharshit/personalcapital/blob/master/requirements.txt
Not sure why it isn't installed when it installed the new dependency

**Comment by raman325** [comment]
~~It needs to be added to the manifest.json dependencies list in the integration folder. HA does not use requirements.txt~~

Sorry I misunderstood how you implemented it. You would instead need to add an install_requires list in setup.py. Both requests and cloud scraper should be in there, the reason it worked in HA before is that HA core installs requests by default

**Comment by sanghviharshit** [comment]
Updated. Thanks for the tip.

**Comment by markmonroy** [comment]
Thanks so much for the fork. I had used this sensor extensively and was missing it a lot.

**Comment by ecoen66** [comment]
Agreed. Thank’s for forking and fixing!


Sent from Yahoo Mail for iPhone


On Saturday, January 15, 2022, 7:21 AM, markmonroy ***@***.***> wrote:




Thanks so much for the fork. I had used this sensor extensively and was missing it a lot.

**Comment by markmonroy** [comment]
@sanghviharshit Are you still using your fork of this integration? A while back mine stopped pulling in data for individual accounts. It still pulls in totals for net worth, investment, and cash.

**Comment by sanghviharshit** [comment]
Yes, I'm using my fork and it stopped pulling in data for individual accounts. I haven't looked in to it though :(

**Comment by sanghviharshit** [comment]
@markmonroy I looked into the missing attributes and updated my fork. Let me know if you still see any issues.

**Comment by sanghviharshit** [comment]
It also includes the changes to the personalcapital library based on this https://github.com/haochi/personalcapital/pull/24

**Comment by markmonroy** [comment]
Hey, it works! Thanks very much!

**Comment by pixelthorn** [comment]
I know this is old but I though I'd point out that there is an updated python library for personal capital at https://github.com/ChocoTonic/personalcapital-py
